FROM continuumio/miniconda3:4.8.2
RUN conda install --yes -c conda-forge \
    nomkl \
    poppler
RUN rm -rf /app && \
    mkdir -p /app/data/
ADD ./fargate /app
RUN pip install --upgrade pip
RUN cd /app && \
    pip install -r requirements.txt
EXPOSE 80
WORKDIR /app
CMD ["uvicorn", "app:api", "--host", "0.0.0.0", "--port", "80"]
